import joplin from 'api';

// Allow console.*: In mobile plugins, console.log is the way to add Joplin's log file (in debug mode).
/* eslint-disable no-console */

const { loadModule } = require('./vendor/sherpa/sherpa-onnx-wasm-main-asr');
const { createOnlineRecognizer } = require('./vendor/sherpa/sherpa-onnx-asr');

const voiceTypingAssets = (languageCode: string, baseUrl: string) => {
	const asset = (suffix: string, prefix: string = languageCode) => {
		const fileName = `${prefix}${suffix}`;
		return {
			url: `${baseUrl}/${fileName}`,
			fileName,
		};
	};

	return [
		asset('__sherpa-onnx-wasm-main-asr.data'),
		asset('sherpa-onnx-wasm-main-asr.wasm', ''),
	];
};
type VoiceTypingAssets = ReturnType<typeof voiceTypingAssets>;

const downloadVoiceTypingAssets = async (assets: VoiceTypingAssets) => {
	for (const asset of assets) {
		const cachePath = asset.fileName;
		if (!await joplin.fs.exists(cachePath)) {
			console.info('Fetching', asset.url);
			await joplin.fs.fetchBlob(asset.url, { outputPath: cachePath });
		} else {
			console.log('already exists', asset.url);
		}
	}
};

interface OnlineRecognizerStream {
	acceptWaveform(sampleRate: number, samples: Float32Array);
}

interface RecognizerResult {
	text: string;
}

interface OnlineRecognizer {
	config: {
		modelConfig: {
			paraformer: {
				encoder: string;
			};
		};
	};
	createStream(): OnlineRecognizerStream;
	isReady(stream: OnlineRecognizerStream): boolean;
	decode(stream: OnlineRecognizerStream): void;
	isEndpoint(stream: OnlineRecognizerStream): boolean;
	getResult(stream: OnlineRecognizerStream): RecognizerResult;
	reset(stream: OnlineRecognizerStream): void;
}

type OnTextProcessed = (text: string)=> Promise<void>;
interface ModuleCallbacks {
	onPreview: OnTextProcessed;
	onFinalize: OnTextProcessed;
}

class VoiceTypingModule {
	private recognizerStream_: OnlineRecognizerStream;
	private lastResult_ = '';
	// True if the last output added was a paragraph break
	private lastWasParagraph_ = false;

	private constructor(private recognizer_: OnlineRecognizer, private callbacks_: ModuleCallbacks) {
		this.recognizerStream_ = recognizer_.createStream();
	}

	private static dataFileCache_: string;
	private static async loadDataFile_(assets: VoiceTypingAssets) {
		if (this.dataFileCache_) return this.dataFileCache_;
		const asset = assets.find(asset => asset.fileName.endsWith('asr.data'));
		const data = await joplin.fs.readBlob(asset.fileName);
		const url = URL.createObjectURL(data);
		this.dataFileCache_ = url;
		return url;
	}

	public static async create(assets: VoiceTypingAssets, callbacks: ModuleCallbacks) {
		const wasm = await joplin.fs.readBlob('./sherpa-onnx-wasm-main-asr.wasm');
		const dataFileUrl = await this.loadDataFile_(assets);

		const { Module, FS } = await loadModule({
			wasmBinary: await wasm.arrayBuffer(),
			locateFile: (f: string) => {
				if (f.includes('sherpa-onnx-wasm-main-asr.data')) {
					return dataFileUrl;
				}
				return f;
			},
		});

		for (const asset of assets) {
			console.log('transferring asset', asset);
			// See https://emscripten.org/docs/api_reference/Filesystem-API.html#filesystem-api
			const stream = FS.open(asset.fileName.replace(/^[a-z]{2}_/, ''), 'w+');
			const array = new Uint8Array(await (await joplin.fs.readBlob(asset.fileName)).arrayBuffer());
			FS.write(stream, array, 0, array.length, 0);
			FS.close(stream);
		}

		const recognizer = createOnlineRecognizer(Module);
		return new VoiceTypingModule(recognizer, callbacks);
	}

	// See https://huggingface.co/spaces/Banafo/Kroko-Streaming-ASR-Wasm/blob/main/app-asr.js
	// and the default app-asr.js generated by sherpa-onnx.
	public async onAudio(audio: Float32Array, sampleRate: number) {
		if (sampleRate !== 16000) {
			throw new Error(`Unsupported audio sample rate ${sampleRate}`);
		}

		this.recognizerStream_.acceptWaveform(sampleRate, audio);
		while (this.recognizer_.isReady(this.recognizerStream_)) {
			this.recognizer_.decode(this.recognizerStream_);
		}

		const result = this.recognizer_.getResult(this.recognizerStream_).text;
		if (result.length) {
			this.lastResult_ = result.trim();
		}

		const isEndpoint = this.recognizer_.isEndpoint(this.recognizerStream_);
		if (isEndpoint) {
			if (this.lastResult_.length) {
				await this.callbacks_.onFinalize(this.lastResult_);
				this.lastWasParagraph_ = false;
				this.lastResult_ = '';
			} else if (!this.lastWasParagraph_) {
				this.lastWasParagraph_ = true;
				await this.callbacks_.onFinalize('\n\n');
			}
			await this.callbacks_.onPreview('');
			this.recognizer_.reset(this.recognizerStream_);
		} else {
			await this.callbacks_.onPreview(this.lastResult_);
		}
	}
}

joplin.plugins.register({
	onStart: async function() {
		const languageCode = 'en';
		const assets = voiceTypingAssets(languageCode, 'http://localhost:8000');
		const isDownloaded = async () => {
			for (const asset of assets) {
				if (!await joplin.fs.exists(asset.fileName)) {
					return false;
				}
			}
			return true;
		};

		let recognizer: VoiceTypingModule;
		await joplin.voiceTyping.registerProvider({
			name: 'Kroko',
			id: 'kroko',
			attribution: {
				url: 'https://huggingface.co/Banafo/Kroko-ASR',
				libraryName: 'Kroko',
			},
			async download() {
				await downloadVoiceTypingAssets(assets);
			},
			async isDownloaded() {
				return await isDownloaded();
			},
			async canUpdateModel() {
				return !await isDownloaded();
			},
			async clearCache() {
				for (const asset of assets) {
					await joplin.fs.remove(asset.fileName);
				}
			},
			async onStart(sessionId) {
				recognizer = await VoiceTypingModule.create(assets, {
					onPreview: (text) => {
						return joplin.voiceTyping.updateRecognitionPreview(sessionId, text);
					},
					onFinalize: (text) => {
						return joplin.voiceTyping.onTextRecognised(sessionId, text);
					},
				});

				void (async () => {
					while (true) {
						const audioData = await joplin.voiceTyping.nextAudioData(sessionId, 3);
						if (!audioData || audioData.data.length === 0) return;
						await recognizer.onAudio(audioData.data, audioData.sampleRate);
					}
				})();
			},
			async onStop(sessionId) {
				console.log('Stopped voice typing session', sessionId);
			},
		});

	},
});
